[package]
org = "joachimDenner"
name = "neon_pg_crud_api"
version = "0.1.0"

[[platform]]
target = "java17"

[build-options]
observabilityIncluded = true

[ballerina.config]
# Dessa nycklar kommer du sedan ange i Choreo UI
required = ["dbHost", "dbUser", "dbPassword", "dbName"]
